### ISSUE TITLE
|BACK-END| Documentar ativamente a API no Postman#75

### ISSUE THREAD

**Issue by Lfelipe-Freitas** [Lfelipe-Freitas/helpr-back-jfs5#4]
Esta tarefa não apenas requer aplicar os endpoints e fazer publicação da documentação final. Os requisitos desta tarefa são:

Uso de variáveis no Postman para a URL Base e para o Token de Usuário;
Nomear as requisições com base no endpoint;
Fazer uso de exemplos para a mesma requisição;
Descrever e detalhar bem os textos da documentação.
A entrega desta tarefa consiste em colocar nos comentários a documentação publicada no postman.

Links úteis:
https://learning.postman.com/docs/sending-requests/variables/
https://learning.postman.com/docs/sending-requests/examples/
https://learning.postman.com/docs/publishing-your-api/documenting-your-api/

**Comment by PettBR** [comment]
- [ ] Uso de variáveis no Postman para a URL Base e para o Token de Usuário - Feito, porém não aparece na documentação.
- [ ] Nomear as requisições com base no endpoint;
- [ ] Fazer uso de exemplos para a mesma requisição;
- [ ] Descrever e detalhar bem os textos da documentação.

Link da documentação do Postman:
> https://documenter.getpostman.com/view/24106290/2s8YzQWPQD
